[package]
name = "lidar-ld19"
version = "0.1.0"
edition = "2021"
authors = ["12345qiupeng <>"]
readme = "README.md"

[dependencies]
lidar = { path = "../lidar" }
serial-port = { path = "../serial-port" }
